import { useEffect, useRef, useState } from "react";

// The greeting clip is generated by scripts/make-tyga-demo.mjs (xAI TTS, voice "carina").
// Live replies come from the Pages Function at /api/tyga (Grok + xAI TTS).
const INTRO = { who: "tyga", text: "Hi, I'm TYGA. Ready to analyze your swing, or get some tips?", clip: "/audio/tyga-intro.mp3" };
const SUGGESTIONS = ["Why do I slice my driver?", "How do I fix early extension?", "What does SwingView measure?"];

// ── particle field ───────────────────────────────────────────────────────────
function buildParticles() {
  const pts = [];
  const rand = (a, b) => a + Math.random() * (b - a);

  // sphere — fibonacci distribution
  const N = 2800;
  const golden = Math.PI * (3 - Math.sqrt(5));
  for (let i = 0; i < N; i++) {
    const y = 1 - (i / (N - 1)) * 2;
    const r = Math.sqrt(1 - y * y);
    const th = golden * i;
    const R = 1 * rand(0.97, 1.0);
    pts.push({ x: Math.cos(th) * r * R, y: y * R, z: Math.sin(th) * r * R, kind: 0, s: rand(0.8, 1.8), seed: Math.random() * 6.28 });
  }
  // rings — three bands, with gaps, denser near edges
  const bands = [
    [1.35, 1.75, 3600],
    [1.85, 2.15, 2400],
    [2.25, 2.45, 1500],
  ];
  for (const [r0, r1, n] of bands) {
    for (let i = 0; i < n; i++) {
      const a = Math.random() * Math.PI * 2;
      const u = Math.random();
      const r = r0 + (r1 - r0) * (0.5 - 0.5 * Math.cos(u * Math.PI));
      pts.push({ x: Math.cos(a) * r, y: rand(-0.015, 0.015), z: Math.sin(a) * r, kind: 1, s: rand(0.7, 2.0), seed: Math.random() * 6.28, r });
    }
  }
  // dust
  for (let i = 0; i < 420; i++) {
    pts.push({ x: rand(-4.2, 4.2), y: rand(-2.6, 2.6), z: rand(-3, 3), kind: 2, s: rand(0.6, 1.6), seed: Math.random() * 6.28, vx: rand(-0.02, 0.02), vy: rand(-0.015, 0.015) });
  }
  return pts;
}

// palette: deep green → mint → acid yellow-green
function tone(k, bright) {
  // k 0..1 picks hue position, bright 0..1 alpha/lightness
  const g1 = [34, 210, 110];   // mint green
  const g2 = [200, 255, 0];    // acid
  const r = Math.round(g1[0] + (g2[0] - g1[0]) * k);
  const g = Math.round(g1[1] + (g2[1] - g1[1]) * k);
  const b = Math.round(g1[2] + (g2[2] - g1[2]) * k);
  return `rgba(${r},${g},${b},${bright.toFixed(3)})`;
}

export default function TygaOrb() {
  const canvasRef = useRef(null);
  const levelRef = useRef(0);          // 0..1 voice level, smoothed
  const targetRef = useRef(0);
  const [mode, setMode] = useState("idle");        // idle | intro | ready | listening | thinking | speaking | done
  const [caption, setCaption] = useState(null);    // { who: "you"|"tyga", text }
  const [draft, setDraft] = useState("");
  const [turnsLeft, setTurnsLeft] = useState(null);
  const [typing, setTyping] = useState(false);
  const historyRef = useRef([]);
  const audioRef = useRef(null);   // { ctx, an, el }
  const recRef = useRef(null);
  const aliveRef = useRef(true);

  // ── render loop ──
  useEffect(() => {
    const canvas = canvasRef.current;
    const ctx = canvas.getContext("2d");
    const pts = buildParticles();
    let raf, t0 = performance.now(), W = 0, H = 0, dpr = 1;

    const resize = () => {
      dpr = Math.min(window.devicePixelRatio || 1, 2);
      W = canvas.clientWidth; H = canvas.clientHeight;
      canvas.width = W * dpr; canvas.height = H * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };
    resize();
    const ro = new ResizeObserver(resize); ro.observe(canvas);

    const tiltX = -0.36, tiltZ = 0.16; // ring tilt
    const cX = Math.cos(tiltX), sX = Math.sin(tiltX), cZ = Math.cos(tiltZ), sZ = Math.sin(tiltZ);

    const frame = (now) => {
      const t = (now - t0) / 1000;
      // smooth the voice level
      levelRef.current += (targetRef.current - levelRef.current) * 0.18;
      const lv = levelRef.current;

      ctx.clearRect(0, 0, W, H);
      const cx = W / 2, cy = H * 0.5;
      const scale = Math.min(W * 0.175, H * 1.6 * 0.185);
      const dens = Math.min(1, W / 1000); const aMul = 0.4 + 0.6 * dens, sMul = 0.65 + 0.35 * dens;
      const rotY = t * 0.12;                       // slow spin
      const drift = Math.sin(t * 0.5) * 0.02;       // gentle breathing at rest
      const puff = 1 + drift + lv * 0.14;           // voice pulse
      const cR = Math.cos(rotY), sR = Math.sin(rotY);

      // glow behind sphere
      const glow = ctx.createRadialGradient(cx, cy, 0, cx, cy, scale * 2.6);
      glow.addColorStop(0, `rgba(60,255,140,${0.16 + lv * 0.14})`);
      glow.addColorStop(0.45, `rgba(60,200,110,${0.06 + lv * 0.06})`);
      glow.addColorStop(1, "rgba(0,0,0,0)");
      ctx.fillStyle = glow; ctx.fillRect(0, 0, W, H);

      ctx.globalCompositeOperation = "lighter";
      for (let i = 0; i < pts.length; i++) {
        const p = pts[i];
        let x, y, z;
        if (p.kind === 2) {
          p.x += p.vx * 0.016 * 60 * 0.02; p.y += p.vy * 0.016 * 60 * 0.02;
          if (p.x > 4.4) p.x = -4.4; if (p.x < -4.4) p.x = 4.4;
          if (p.y > 2.8) p.y = -2.8; if (p.y < -2.8) p.y = 2.8;
          x = p.x; y = p.y; z = p.z;
        } else {
          // ring ripple travels outward with the voice
          let rr = 1;
          if (p.kind === 1) rr = 1 + Math.sin(t * 2.2 - p.r * 2.5 + p.seed * 0.3) * (0.01 + lv * 0.05);
          const px = p.x * puff * rr, py = p.y * puff, pz = p.z * puff * rr;
          // spin about Y
          const x1 = px * cR - pz * sR, z1 = px * sR + pz * cR, y1 = py;
          // tilt about X then Z
          const y2 = y1 * cX - z1 * sX, z2 = y1 * sX + z1 * cX;
          x = x1 * cZ - y2 * sZ; y = x1 * sZ + y2 * cZ; z = z2;
        }
        const persp = 1 / (1 + z * 0.14);
        const sx = cx + x * scale * persp, sy = cy + y * scale * persp;
        if (sx < -4 || sx > W + 4 || sy < -4 || sy > H + 4) continue;

        const depth = (z + 2.5) / 5; // 0 far .. 1 near
        const twinkle = 0.75 + 0.25 * Math.sin(t * 1.7 + p.seed);
        let k, a, size;
        if (p.kind === 0) { k = 0.15 + depth * 0.4; a = (0.45 + depth * 0.55) * twinkle; size = p.s * (0.9 + depth * 1.1); }
        else if (p.kind === 1) { const edge = (p.r - 1.35) / 1.1; k = 0.3 + edge * 0.7; a = (0.35 + depth * 0.55) * twinkle; size = p.s * (0.75 + depth * 1.0); }
        else { k = 0.25; a = 0.2 * twinkle; size = p.s * 1.0; }
        a = Math.min(1, a * aMul * (1 + lv * 0.5)); size *= sMul;
        ctx.fillStyle = tone(k, a);
        ctx.beginPath(); ctx.arc(sx, sy, size * persp, 0, 6.283); ctx.fill();
      }
      ctx.globalCompositeOperation = "source-over";
      raf = requestAnimationFrame(frame);
    };
    raf = requestAnimationFrame(frame);
    return () => { cancelAnimationFrame(raf); ro.disconnect(); };
  }, []);

  // ── audio engine: one AudioContext + analyser shared by every clip ──
  const ensureAudio = () => {
    if (audioRef.current) return audioRef.current;
    const ctx = new (window.AudioContext || window.webkitAudioContext)();
    const an = ctx.createAnalyser(); an.fftSize = 512; an.smoothingTimeConstant = 0.6;
    an.connect(ctx.destination);
    const buf = new Uint8Array(an.frequencyBinCount);
    const state = { ctx, an, el: null, speaking: false, pulse: 0 };
    const tick = () => {
      if (!aliveRef.current) return;
      if (state.speaking) {
        an.getByteFrequencyData(buf);
        let sum = 0; for (let i = 2; i < 40; i++) sum += buf[i];
        targetRef.current = Math.min(1, (sum / 38 / 255) * 1.8);
      } else if (state.pulse) {
        targetRef.current = state.pulse * (0.3 + 0.2 * Math.abs(Math.sin(performance.now() / 450)));
      } else {
        targetRef.current = 0;
      }
      requestAnimationFrame(tick);
    };
    tick();
    audioRef.current = state;
    return state;
  };

  const speak = (src) => new Promise((resolve) => {
    const a = ensureAudio();
    if (a.ctx.state === "suspended") a.ctx.resume();
    if (a.el) { a.el.pause(); a.el.src = ""; }
    const el = new Audio(src); el.crossOrigin = "anonymous";
    a.ctx.createMediaElementSource(el).connect(a.an);
    a.el = el; a.speaking = true; a.pulse = 0;
    const done = () => { a.speaking = false; resolve(); };
    el.onended = done; el.onerror = done;
    el.play().catch(done);
  });

  const stopSpeaking = () => {
    const a = audioRef.current;
    if (a?.el) { a.el.pause(); a.el.src = ""; a.speaking = false; }
  };

  useEffect(() => () => { aliveRef.current = false; stopSpeaking(); recRef.current?.abort?.(); }, []);

  // ── intro ──
  const startDemo = async () => {
    if (mode !== "idle" && mode !== "done") return;
    setMode("intro"); setCaption(INTRO); historyRef.current = []; setTurnsLeft(null);
    const ok = await fetch(INTRO.clip, { method: "HEAD" }).then((r) => r.ok && /audio/.test(r.headers.get("content-type") || "")).catch(() => false);
    if (ok) await speak(INTRO.clip);
    else { const a = ensureAudio(); a.pulse = 1; await new Promise((r) => setTimeout(r, 2200)); a.pulse = 0; }
    if (aliveRef.current) setMode("ready");
  };

  // ── one conversational turn ──
  const ask = async (text) => {
    const q = (text || "").trim();
    if (!q || mode === "thinking" || mode === "speaking") return;
    stopSpeaking(); recRef.current?.abort?.();
    setDraft(""); setTyping(false);
    historyRef.current = [...historyRef.current, { role: "user", content: q }];
    setCaption({ who: "you", text: q });
    setMode("thinking");
    const a = ensureAudio(); a.pulse = 0.6;
    const thoughts = ["Thinking about your swing…", "Checking the numbers…", "Putting it in golfer terms…"];
    let ti = 0; const thinkTimer = setInterval(() => { ti = Math.min(ti + 1, thoughts.length - 1); setCaption({ who: "tyga", text: thoughts[ti], soft: true }); }, 2200);
    setTimeout(() => setCaption({ who: "tyga", text: thoughts[0], soft: true }), 900);
    let data;
    try {
      const r = await fetch("/api/tyga", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: historyRef.current }), signal: AbortSignal.timeout(45000) });
      data = await r.json().catch(() => ({}));
      if (r.status === 429) { data.limit = true; }
      else if (!r.ok) throw new Error(data.error || r.status);
    } catch (err) {
      console.error(err);
      data = { text: err?.name === "TimeoutError" ? "That took longer than it should — give me one more try." : "I'm having a little trouble right now — try me again in a moment." };
    }
    clearInterval(thinkTimer);
    a.pulse = 0;
    if (!aliveRef.current) return;
    const reply = data.text || "Say that again?";
    historyRef.current = [...historyRef.current, { role: "assistant", content: reply }];
    setCaption({ who: "tyga", text: reply });
    if (typeof data.turnsLeft === "number") setTurnsLeft(data.turnsLeft);
    setMode("speaking");
    if (data.audio) {
      const bin = atob(data.audio); const bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
      const url = URL.createObjectURL(new Blob([bytes], { type: "audio/mpeg" }));
      await speak(url); URL.revokeObjectURL(url);
    } else {
      a.pulse = 1; await new Promise((r) => setTimeout(r, Math.min(6000, 1500 + reply.length * 45))); a.pulse = 0;
    }
    if (!aliveRef.current) return;
    setMode(data.limit || data.turnsLeft === 0 ? "done" : "ready");
  };

  // ── microphone (Web Speech API) ──
  const SR = typeof window !== "undefined" ? window.SpeechRecognition || window.webkitSpeechRecognition : null;
  const listen = () => {
    if (!SR) { setTyping(true); return; }
    if (mode === "listening") { recRef.current?.stop?.(); return; }
    stopSpeaking();
    const rec = new SR(); rec.lang = "en-US"; rec.interimResults = true; rec.maxAlternatives = 1;
    recRef.current = rec;
    let finalText = "";
    rec.onresult = (e) => {
      let interim = "";
      for (let i = e.resultIndex; i < e.results.length; i++) {
        const t = e.results[i][0].transcript;
        if (e.results[i].isFinal) finalText += t; else interim += t;
      }
      setCaption({ who: "you", text: (finalText || interim).trim() || "Listening…" });
    };
    rec.onerror = () => { setMode("ready"); if (!finalText) setCaption({ who: "tyga", text: "I didn't catch that — tap the mic and try again, or type it below." }); };
    rec.onend = () => { if (finalText.trim()) ask(finalText); else if (mode === "listening") setMode("ready"); };
    setMode("listening"); setCaption({ who: "you", text: "Listening…" });
    const a = ensureAudio(); a.pulse = 0.35;
    try { rec.start(); } catch { setMode("ready"); }
  };

  const busy = mode === "thinking" || mode === "speaking";
  const live = mode !== "idle" && mode !== "intro";

  return (
    <div className="tyga">
      <div className="tyga-eyebrow">Meet TYGA</div>
      <h2 className="tyga-title">Your swing. A real conversation.</h2>
      <div className="tyga-stage">
        <canvas ref={canvasRef} className="tyga-canvas" aria-hidden="true" />
      </div>

      {!live ? (
        <button type="button" className={"tyga-player" + (mode === "intro" ? " on" : "")} onClick={startDemo} aria-pressed={mode === "intro"}>
          <span className="tyga-play">
            {mode === "intro" ? (
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="6" y="5" width="4" height="14" rx="1" /><rect x="14" y="5" width="4" height="14" rx="1" /></svg>
            ) : (
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8 5v14l11-7z" /></svg>
            )}
          </span>
          <span className="tyga-label">{mode === "intro" ? "TYGA is talking" : "Talk to TYGA"}</span>
          <Wave levelRef={levelRef} playing={mode === "intro"} />
        </button>
      ) : (
        <div className="tyga-talk">
          <div className={"tyga-bar" + (mode === "listening" ? " listening" : "") + (busy ? " busy" : "")}>
            <button type="button" className="tyga-mic" onClick={listen} disabled={busy || mode === "done"} aria-label={mode === "listening" ? "Stop listening" : "Talk to TYGA"}>
              {mode === "listening" ? (
                <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2" /></svg>
              ) : (
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="9" y="3" width="6" height="11" rx="3" /><path d="M5 11a7 7 0 0 0 14 0M12 18v3" /></svg>
              )}
            </button>
            <form className="tyga-form" onSubmit={(e) => { e.preventDefault(); ask(draft); }}>
              <input
                value={draft}
                onChange={(e) => setDraft(e.target.value)}
                onFocus={() => setTyping(true)}
                disabled={busy || mode === "done"}
                placeholder={mode === "listening" ? "Listening…" : mode === "thinking" ? "TYGA is thinking…" : mode === "speaking" ? "TYGA is talking…" : mode === "done" ? "Preview finished" : SR ? "Tap the mic or type a question" : "Type a question for TYGA"}
                aria-label="Ask TYGA a question"
                maxLength={300}
              />
              <button type="submit" className="tyga-send" disabled={busy || mode === "done" || !draft.trim()} aria-label="Send">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M12 19V5M5 12l7-7 7 7" /></svg>
              </button>
            </form>
            <Wave levelRef={levelRef} playing={mode === "speaking" || mode === "listening"} />
          </div>
          {mode === "ready" && historyRef.current.length === 0 && (
            <div className="tyga-chips">
              {SUGGESTIONS.map((q) => <button key={q} type="button" onClick={() => ask(q)}>{q}</button>)}
            </div>
          )}
          {mode === "done" && (
            <a href="#waitlist" className="btn btn-white tyga-cta">Get the app to keep talking</a>
          )}
        </div>
      )}

      <div className="tyga-sub">
        {live && typeof turnsLeft === "number" && mode !== "done" ? `${turnsLeft} question${turnsLeft === 1 ? "" : "s"} left in this preview` : "A preview of your live AI swing coach"}
      </div>
      <div className="tyga-caption" aria-live="polite">
        {caption ? (
          <span className={caption.who === "you" ? "you" : caption.soft ? "soft" : "ai"}>{caption.who === "you" ? `“${caption.text}”` : caption.text}</span>
        ) : (
          <span className="ai">“{INTRO.text}”</span>
        )}
      </div>
    </div>
  );
}

// 18-bar waveform that follows the voice level
function Wave({ levelRef, playing }) {
  const ref = useRef(null);
  useEffect(() => {
    let raf;
    const bars = ref.current.children;
    const seeds = Array.from({ length: bars.length }, () => Math.random() * 6.28);
    const tick = (now) => {
      const t = now / 1000, lv = levelRef.current;
      for (let i = 0; i < bars.length; i++) {
        const mid = 1 - Math.abs(i - (bars.length - 1) / 2) / ((bars.length - 1) / 2);
        const idle = 0.18 + 0.12 * Math.sin(t * 2 + seeds[i]);
        const live = 0.25 + lv * (0.45 + 0.55 * Math.abs(Math.sin(t * 9 + seeds[i] * 2))) * (0.5 + mid * 0.7);
        const h = playing ? live : idle;
        bars[i].style.transform = `scaleY(${Math.min(1, h).toFixed(3)})`;
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [levelRef, playing]);
  return (
    <span ref={ref} className="tyga-wave" aria-hidden="true">
      {Array.from({ length: 18 }).map((_, i) => <i key={i} />)}
    </span>
  );
}
